In [1]:
from datetime import date
today = date.today()
print("Last Updated Date:", today.strftime("%d %B %Y"))

Last Updated Date: 25 May 2021


<br>[NumPy - Linear Algebra Library for Python](#NumPy_Linear_Algebra_Library_for_Python)
<br>[Numpy CheatSheet](#Numpy_CheatSheet)
<br>[Numpy Arrays / Matrices](#Numpy_Arrays_/_Matrices)
<br>[Array Attribute(s) or Property(s)](#Array_Attribute)
<br>[Array Methods / Fucntions](#Array_Methods_Fucntions)
<br>[NumPy Indexing (Bracket Indexing) and Selection](#NumPy_Indexing_and_Selection)
<br>[NumPy Operations](#NumPy_Operations)
<br>[Summary Statistics on NumPy Arrays](#Summary_Statistics_on_Arrays)
<br>[Axis Logic](#Axis_Logic)
<br>[Random Library](#Random_Library)
<br>[Built-in Functions](#Built-in_Functions)

# <a id='NumPy_Linear_Algebra_Library_for_Python'></a>NumPy - Linear Algebra Library for Python

* NumPy is a powerful __linear algebra library__ for Python, What makes it so important is that almost all of the libraries in the <a href='https://pydata.org/'>PyData</a> ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks.
* Numpy is also incredibly fast, as it has bindings to C libraries. __For more info on why you would want to use Numpy Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).__
* Numpy has many built-in functions and capabilities

# <a id='Numpy_CheatSheet'></a>Numpy CheatSheet

* conda install numpy
* import numpy as np

## Casting List into Arrays/Matrices
* mat = np.array(my_list)
* type(mat)  - numpy.ndarray

## Range in Matrices/Arrays
* np.arange(start,stop,step,dtype)

##  Linear Space
* np.linspace(start,stop,linspace)

## Zeros and Ones
* np.zeros(size,dtype)
* np.one(size,dtype)
* np.identity(n,dtype)

## Random Number Generation in Arrays / Matrices
* np.random
* np.random.randint(i,e,size)
* np.random.normal(i,e,size) # Works based on Gaussian Product
* np.random.rand()
* np.random.randn() # Works based on Standard Distribution

## Matrix / Array Operations
* arr.size
* arr.dtype
* arr.max()
* arr.min()
* arr.mean()
* arr.argmax()          # We can also write like this argmax(arr)
* arr.reshape(size)

## Example of Stacked Methods
* mat = np.arange(0,100).reshape(10,10)

## Matrices Slicing
* mat[0,0]
* mat[0,1]
* mat[4,3]
* mat[:,0]
* mat[3,:]
* mat[0:3,0:3]  # 0:3 means [0,3
* mat[1:5,3:6]  # 1:5 means [1:5) and 3:6 means [3,6)

## Boolean Masking
* mat[mat>50]
* ( # Same as Above
  my_filter = mat>50
  mat[my_filter]
  )

## NumPy Operations and Universal Array Functions
* arr+arr, arr-arr,arr/arr, arr* arr, arr**
* np.sqrt(arr), np.sin(arr), np.exp(arr), np.log(arr)

In [2]:
                                            # Questions
# To see all the libraries in the Module
# To see the Help Section of a particular command
# Casting List into Arrays/Matrices
# To know the 'Type' of the Matrices
# Range in Arrays (Directly creating Arrays instead from the lists)
# Linear space between the number generation (Returns evenly spaced numbers over specified interval)
# Zeros and Ones
# Random Number Generations in Array/Matrices
# Matrix / Array Operations (min,max,size,argmax,reshape....)
# Examples of Stacked Operations on Matrices
# Matrix Slicing
# Boolean Masking
# Create Identity matrix
# Give some examples of attributes and methods on Arrays
# Difference between np.random.rand, np.random.randn, np.random.randint

In [ ]:
# Practice Session
import numpy as np
myl = [i for i in range(10)]
arr = np.array(myl)
arr
type(arr)
myl2 = np.arange(0,11,1,np.float32)
myl2
np.zeros(5,np.float32)
np.ones((3,4),np.float64)
np.random.randint(0,10,(3,2),np.int32)
np.random.rand
np.random.randn
myl3 = np.linspace(0,11,10).reshape(2,5)
myl3
mat = np.arange(100,dtype = np.int64).reshape(10,10)
mat
mat.argmax()
mat.min()
mat.max()
mat[0,0]
print(mat)
mat[0:3,:]
mat[7:10,4:7]
mat[mat>10]
np.eye(3)
mat.size     - These are attributes (Properties)
arr.shape    - These are attributes (Properties)
arr.dtype    - These are attributes (Properties)
np.random.randint(0,10,(3,2)).size
np.sin(mat)
np.cos(arr)
np.sqrt(arr)
np.sum(axis=0) (summation along rows)
np.sum(axis=1) (summation along columns)
mat[:,0]    # Colon (:) is used to indicate everything. It is similar to slicing in the list
arr.reshape()  - Most commonly used

# <a id='Numpy_Arrays_/_Matrices'></a>Numpy Arrays / Matrices
* Numpy arrays essentially come in two flavors: __vectors__ and __matrices (multi-dimensional arrays)__. Vectors are strictly 1-D arrays and matrices are 2-D (but you should note a matrix can still have only one row or one column)

## Creating NumPy Arrays / Matrices from a Python List
* We can create an array by directly converting a list or list of lists

In [3]:
import numpy as np

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# <a id='Array_Attribute'></a>Array Attribute(s) or Property(s)
* Let's discuss some useful attributes for an array:

## Shape
Shape is an attribute that arrays have (not a method)

In [8]:
# Vector
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
# Arrays / Matrices are vectors which have magnitude and direction (x,y,z.....)
arr.shape

(25,)

In [10]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [11]:
arr.reshape(1,25).shape

(1, 25)

## Size
Size is an attribute that arrays / matrices have

In [12]:
arr.size

25

## dtype

You can also grab the data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [13]:
arr.dtype

dtype('int32')

In [14]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

# <a id='Array_Methods_Fucntions'></a>Array Methods / Fucntions

## reshape
* Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [15]:
arr.reshape(5,5)   #reshape() method is commonly used

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
mat = np.arange(0,100).reshape(10,10)  #This type is called Stacked Methods

In [17]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [18]:
mat[0,1] # This is the matrix notation and I always prefer this notation, because of simlicity and you can same syntax for variety of selections

1

In [19]:
mat[0][1] # This is a list Notation and gives the same result as above

1

In [20]:
mat[4,3]

43

In [21]:
#### Get the sum of all the rows in mat
mat.sum(axis=0)

array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

In [22]:
#### Get the sum of all the columns in mat
mat.sum(axis=1)

array([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

In [23]:
mat[:,0]    # Colon (:) is used to indicate everything. It is similar to slicing in the list

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
mat[0,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
mat[:,4]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [26]:
 mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

## max,min,argmax,argmin   (These are Methods and are not Attributes / Property)
* These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [27]:
arr = np.arange(0,25)

In [28]:
arr.max()

24

In [29]:
arr.argmax()

24

In [30]:
arr.min()

0

In [31]:
arr.argmin()

0

In [32]:
arr.mean()

12.0

# <a id='NumPy_Indexing_and_Selection'></a>NumPy Indexing (Bracket Indexing) and Selection
* Selecting elements or groups of elements from an array
* The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [33]:
#Creating sample array
arr = np.arange(0,11)

In [34]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
#Get a value at an index
arr[8]

8

In [36]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

## Indexing a 2D array (matrices)

* The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend using the comma notation for clarity

In [43]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [45]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [46]:
# Getting individual element value
arr_2d[1,0]

20

In [47]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [48]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [49]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## More Indexing Help
Indexing a 2D matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching *NumPy indexing* to find useful images, like this one:
<br>![](./Media/numpy_indexing.png)

## Broadcasting
* NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [37]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [38]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [40]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [41]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [42]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Conditional Selection
* This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part!

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [50]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [52]:
bool_arr = arr>4

In [53]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [54]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [55]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [57]:
# Boolean Masking Example
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [58]:
my_filter = mat>50

In [59]:
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [60]:
#Instead of doing in two steps we can just do it in single step
mat[mat>50]          #also boolean masking with no intermidiate variables

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [62]:
mat[5:10,1:10]           # [ - Inclusion, ) - Exclusion

array([[51, 52, 53, 54, 55, 56, 57, 58, 59],
       [61, 62, 63, 64, 65, 66, 67, 68, 69],
       [71, 72, 73, 74, 75, 76, 77, 78, 79],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

# <a id='NumPy_Operations'></a>NumPy Operations

## Arithmetic

You can easily perform *array with array* arithmetic, or *scalar with array* arithmetic. Let's see some examples:

In [63]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [65]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [66]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
# This will raise a Warning on division by zero, but not an error!
# It just fills the spot with nan
arr/arr

C:\Users\sande\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [68]:
# Also a warning (but not an error) relating to infinity
1/arr

C:\Users\sande\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [69]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

NumPy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, which are essentially just mathematical operations that can be applied across the array.<br>Let's show some common ones:

In [70]:
# Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [71]:
# Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [72]:
# Trigonometric Functions like sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [73]:
# Taking the Natural Logarithm
np.log(arr)

C:\Users\sande\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## <a id='Summary_Statistics_on_Arrays'></a>Summary Statistics on NumPy Arrays
* NumPy also offers common summary statistics like <em>sum</em>, <em>mean</em> and <em>max</em>. You would call these as methods on an array
* __Other summary statistics include:__

        * arr.min() returns 0                   minimum
        * arr.var() returns 8.25                variance
        * arr.std() returns 2.8722813232690143  standard deviation

In [74]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr.sum()

45

In [76]:
arr.mean()

4.5

In [77]:
arr.max()

9

# <a id='Axis_Logic'></a>Axis Logic
* When working with 2-dimensional arrays (matrices) we have to consider rows and columns. This becomes very important when we get to the section on pandas. In array terms, axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns). These values (0,1) correspond to the order in which <tt>arr.shape</tt> values are returned.
* In NumPy (__in Pandas it's opposite__),
    * axis = 0, along all rows
    * axis =1, along all columns
    ![](./Media/axis_logic.png)

Let's see how this affects our summary statistic calculations from above.

In [78]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

By passing in <tt>axis=0</tt>, we're returning an array of sums along the vertical axis, essentially <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>
<br>![](./Media/axis_logic.png)

In [80]:
arr_2d.shape

(3, 4)

* This tells us that <tt>arr_2d</tt> has 3 rows and 4 columns.
* In <tt>arr_2d.sum(axis=0)</tt> above, the first element in each row was summed, then the second element, and so forth.
* So what should <tt>arr_2d.sum(axis=1)</tt> return?

In [81]:
# THINK ABOUT WHAT THIS WILL RETURN BEFORE RUNNING THE CELL!
arr_2d.sum(axis=1)

array([10, 26, 42])

In [82]:
type(arr)               #ndarray means N-Dimensional Array

numpy.ndarray

# <a id='Random_Library'></a>Random Library
* Numpy also has lots of ways to create random number arrays:

## rand
* rand - Creates array/matrix of given shape and populates it with random samples from a uniform distribution over ``[0, 1)``

## randn
* randn - Creates array/matrix of given shape based 'Standard Normal' distrubution unlike 'rand' which does uniform distribution

## randint
* randint - Return random integers from `low` (inclusive) to `high` (exclusive)

In [83]:
np.random.rand(3,2)

array([[0.61916652, 0.19933908],
       [0.02532375, 0.66969387],
       [0.97530262, 0.5836863 ]])

In [84]:
np.random.randn(3,2)

array([[-0.05473016, -2.43728469],
       [-0.67181538, -0.81190468],
       [-0.28197196, -0.4419101 ]])

In [85]:
# It is necessary to genearte random numbers in Machine Learning and NUMPY has lot of built in random number generators
np.random.randint(0,10)             #randint - Returns back a random integer. random is frequently used one

7

In [86]:
np.random.randint(0,10,size=10)

array([0, 9, 6, 8, 8, 4, 0, 7, 1, 7])

In [87]:
np.random.randint(0,10,10)

array([8, 3, 8, 2, 7, 9, 5, 5, 4, 0])

In [88]:
np.random.randint(0,10,(3,2))

array([[3, 4],
       [8, 8],
       [0, 8]])

In [89]:
np.random.randint(0,10,(3,2)).size

6

In [90]:
np.random.normal(5,2,(2,3))     # It works based on Gaussian Product 

array([[3.67823052, 4.30230535, 6.778036  ],
       [1.11828222, 5.49358079, 6.49943054]])

__seed can be used to set the random state, so that the same "random" results can be reproduced__

__Always remember 'seed' have to be in the same cell along with your code__

In [91]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [92]:
np.random.seed(101)    #This will make sure random numbers being generated are same everytime
np.random.randint(0,10,10) #Random seed and randint functions has to be in the same cell in order to generate same numbers every time

array([1, 6, 7, 9, 8, 4, 8, 5, 0, 5])

In [93]:
np.random.seed(101)
arr = np.random.randint(0,10,10)

# <a id='Built-in_Functions'></a>Built-in Functions
* There are lots of built-in ways to generate Arrays

## arange
* Return evenly spaced values within a given interval.

In [94]:
np.arange(0,10)         # np.arange function is similar to range function in python but it deals with arrays'

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [96]:
np.arange(0,10,2,np.float64)     # It contains start, stop, jump size and data type

array([0., 2., 4., 6., 8.])

## linspace
Return evenly spaced numbers over a specified interval.

In [97]:
np.linspace(1,10,10)     # It contains start, stop and linear space between the successive numbers

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [98]:
np.linspace(0,10,10)   # It contains start, stop and linear space between the successive numbers. This is the main 
                       # difference betwen arange function and linspace function

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

## zeros and ones
Generate arrays of zeros or ones

In [99]:
np.zeros(5)             # Array list of zeros

array([0., 0., 0., 0., 0.])

In [100]:
np.zeros((3,4))         # Matrix of (3,4) and default datatype is Float

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
np.zeros((3,4),dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [102]:
x = np.ones((3,3))

In [103]:
y = np.ones((3,3),dtype='int')

In [104]:
(x==y).sum()

9

In [105]:
#Set up matrix
arr2d = np.zeros((10,10))


'gjfhgfhgf

In [106]:
#Length of array
arr_length = arr2d.shape[1]

In [107]:
for i in range(arr_length):
    arr2d[i]=i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [108]:
arr2d[6]

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [109]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## eye
Creates an identity matrix

In [110]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [111]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## bincount()
* Count number of occurrences of each value in array of non-negative integers

In [2]:
import numpy as np
# 1D array with +ve integers 
array1 = [1, 6, 1, 1, 1, 2, 2] 
bin = np.bincount(array1)
print("Bincount output  : \n ", bin) 
print("size of bin : ", len(bin), "\n")

Bincount output  : 
  [0 4 2 0 0 0 1]
size of bin :  7 

<class 'numpy.ndarray'>


In [113]:
print(np.nonzero(bin))
print(np.nonzero(bin)[0])

(array([1, 2, 6], dtype=int64),)
[1 2 6]


In [3]:
x = np.array([1,1,1,2,2,2,7,0,25,1,100,0,1])
print(x)
freqcnt = np.bincount(x) # Frequency of occurences of each input in an numpy array at that number's index location
print(freqcnt)

[  1   1   1   2   2   2   7   0  25   1 100   0   1]
[2 5 3 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


In [4]:
indexofnonzeros = np.nonzero(freqcnt)[0]  # Returns the indices of the elements that are non-zero. Eventually gives unique elements in an input (x)
print(indexofnonzeros)    # It gives nothing but actual elements

[  0   1   2   7  25 100]


## vstack()

In [17]:
freqcnt

array([2, 5, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [18]:
freqcnt[[0,1,7]]

array([2, 5, 1], dtype=int64)

In [12]:
print(x)
print(indexofnonzeros)
print(freqcnt[indexofnonzeros])
print('--------------------------')
print(np.vstack((indexofnonzeros,freqcnt[indexofnonzeros])))

[  1   1   1   2   2   2   7   0  25   1 100   0   1]
[  0   1   2   7  25 100]
[2 5 3 1 1 1]
--------------------------
[[  0   1   2   7  25 100]
 [  2   5   3   1   1   1]]


In [7]:
print(np.vstack((indexofnonzeros,freqcnt[indexofnonzeros])).T)      # Numpy's Tranpose function of an input with .T

[[  0   2]
 [  1   5]
 [  2   3]
 [  7   1]
 [ 25   1]
 [100   1]]


In [8]:
print(np.transpose(np.vstack((indexofnonzeros,freqcnt[indexofnonzeros])))) # Numpy's Tranpose function of an input np.transpose()

[[  0   2]
 [  1   5]
 [  2   3]
 [  7   1]
 [ 25   1]
 [100   1]]


In [9]:
print(list(zip(indexofnonzeros,freqcnt[indexofnonzeros])))     # Python's zip also does the same as Tranpose but returns an array of tuples

[(0, 2), (1, 5), (2, 3), (7, 1), (25, 1), (100, 1)]


## squeeze()
* The squeeze() function is used to remove single-dimensional entries from the shape of an array.
* https://www.w3resource.com/numpy/manipulation/squeeze.php

In [116]:
import numpy as np
a = np.array([[[0], [2], [4]]])
print(a.shape)
x = np.squeeze(a)
print(x)
print(np.squeeze(a).shape)

(1, 3, 1)
[0 2 4]
(3,)


## numpy.append()
* Append values to the end of an array
<br>![](./Media/2_59.png)
* https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [2]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])